/*
Copyright © 2020 NAME HERE <EMAIL ADDRESS>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
package cmd

import (
	"errors"
	"fmt"

	"github.com/spf13/cobra"
)

// coreCmd represents the core command
var coreCmd = &cobra.Command{
	Use:   "core <coredump> <executable>",
	Short: "调试内核转储",
	Long:  `调试内核转储`,
	PreRunE: func(cmd *cobra.Command, args []string) error {
		if len(args) != 2 {
			return errors.New("参数非法")
		}
		return nil
	},
	RunE: func(cmd *cobra.Command, args []string) error {
		core := args[0]
		exec := args[1]
		fmt.Printf("debug %s generated by %s\n", core, exec)
		return nil
	},
}

func init() {
	rootCmd.AddCommand(coreCmd)
}
